### ISSUE TITLE
Spectre does not adjust height when using a new shorter baseline

### ISSUE THREAD

**Issue by tk8817** [wearefriday/spectre#14]
see screenshots below where I passed 1200 and 50 respectively. WhenI changed the width, that seemed to kick off some refresh and the height issue was resolved.

http://imgur.com/a/rqFx0

**Comment by tk8817** [comment]
This seemingly only happens if you previously had a baseline which was taller!

**Comment by nickdunn** [comment]
@tk8817 thanks for this. I'm not 100% sure if this is a bug. Each test creates a "canvas" width/height that the baseline and comparison are mounted onto, so that the comparison is clean. The canvas width/height is always the larger, whether that be the baseline or comparison.

So if you started with a 1200x800 image (which is then stored as a baseline), and the next one you submit is 1200x600, the comparison will still be against 1200x800 and will likely fail because the comparison image will have a 1200x200 white bar along the bottom as it's shorter.

However if you then set the new 1200x600 image as the baseline, subsequent tests of the same width would pass.

I know it's been a couple of months since your report (sorry) but would you mind confirming if I'm understanding the bug correctly?

**Comment by nickdunn** [comment]
Looking at the attached screenshot, when you uploaded a screenshot at 1200px tall, you sent "1200" as the `width` parameter. When you uploaded the second screenshot at 50px tall, you passed `50` as `width` parameter. Spectre interprets these are two discrete tests, hence the "refresh" you're seeing — they are two different tests that Spectre is managing. 

If you'd kept the `width` parameter the same and posted 1200px tall then 50px tall (in that order), your screenshots will *always* be 1200px tall, because that's the larger of the two. And if then set your 50px image as the baseline, subsequent runs will still be 1200px tall, because at the point of setting the baseline, Spectre only has the 1200px tall version of your 50px image (it doesn't keep the original unresized version).

Perhaps that's the bug then — if screenshots are resized to the larger of the two canvases, if you later set a smaller image as a baseline, should that baseline use the original asset, rather than the resized canvas?

This is indeed possible if we always store the original asset as well as the resized canvas version. But I'm conscious of storing images unnecessarily which can rapidly eat up disk space at scale.

**Comment by tk8817** [comment]
@nickdunn thanks for following up. I think you fully understand the matter. The most common use case I see is that someone realizes they had too much content in their first upload, changes the size, and then uploads again. As long as they can get 'back to normal' by setting the new image as the baseline, I don't see much harm in how this works.
