### ISSUE TITLE
Provide documentation on optional parameters

### ISSUE THREAD

**Issue by jankcat** [wearefriday/spectre#35]
Hello,

I am looking for information on the different parameters and config

eg: what percentage difference equals a pass or fail, and how to tweak those percentages
eg: what the fuzz_level parameter does
etc.

Does anyone have this information, is there a plan to add it to the documentation here?

**Comment by jankcat** [comment]
Noticed in code... https://github.com/wearefriday/spectre/blob/e347a7ce8df274118d807caf9d00d491bc782479/app/models/screenshot_comparison.rb#L75

**Comment by lanej0** [comment]
I actually changed this so that the diff threshold can be set for different purposes.  In `screenshot_comparison.rb`, I changed it to:

```(test.diff < test.diff_accept)```

Then in `app/models/test.rb` under default values

```self.diff_accept = 5 if self.dif_accept.blank?```

And in `app/controllers/tests_controller.rb`, under `def test_params`

```
:diff_accept
```
to the list of permitted parameters.

That will allow you to set an "acceptable threshold" on a per-test basis (and set a default of "5" if one isn't specified).

**Comment by aaron-humerickhouse** [comment]
I too am wondering about fuzz_level.  What is it and how does it work?

**Comment by Firefishy** [comment]
Spectre hasn't seen active development for some time. Closing the issue, feel free to open at one of the forks.

Alternatively try a fork with active development:

* https://github.com/lanej0/spectre
* https://github.com/octanner/spectre
